FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app sources (will be overridden by volume mount in dev)
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
